# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170822_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='email',
            new_name='category',
        ),
    ]
